apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
spec:
  destination:
    name: ''
    namespace: webapp
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/zyadtarek11/NodejsProjectWithArgoCD.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
