apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web
  namespace: webapp
  labels:
    app: nodejs-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-web
  template:
    metadata:
      labels:
        app: nodejs-web
    spec:
      containers:
      - name: nodejs-web
        image: zyadtarek/argocd
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "200Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000 