apiVersion: v1
kind: Service
metadata:
  name: nodejs-web
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001 # Optional, or let Kubernetes assign one
  selector:
    app: nodejs-web